apiVersion: v1
kind: Pod
metadata:
  name: yolo-backend
  labels:
    app: yolo
    layer: backend
spec:
  containers:
  - image: reagancn/yolo-backend
    name: yolo-backend
    env:
      - name: MONGODB_URI
        value: "MONGODB_URI=mongodb://mongodb:27017/yolomy"
    ports:
    - containerPort: 5050
      protocol: TCP