apiVersion: v1
kind: Pod
metadata:
  name: yolo-backend
  labels:
    app: yolo
    layer: backend
spec:
  containers:
  - image: reaganc/yolo-backend:1.7
    name: yolo-backend
    command: ["npm", "start"]
    stdin: true
    tty: true
    env:
      - name: MONGODB_URI
        value: "MONGODB_URI=mongodb://mongodb:27017/yolomy"
    ports:
    - containerPort: 5050
      protocol: TCP