apiVersion: v1
kind: Pod
metadata:
  name: yolo-client
  labels:
    app: yolo
    layer: frontend
spec:
  containers:
  - image: reaganc/yolo-client:1.6
    name: yolo-client
    command: ["npm", "start"]
    tty: true
    stdin: true
    ports:
    - containerPort: 3000
      protocol: TCP