version: "2.0"
services:
  client:
    build: ./client
    image: yolo-client:1.2
    entrypoint: npm start
    ports:
    - 3000:3000
    tty: true
    networks:
      - custom-network
  backend:
    build: ./backend
    image: yolo-backend:1.2
    environment:
    - MONGODB_URI=mongodb://mongodb:27017/yolomy
    entrypoint: npm start
    ports:
      - 5050:5050
    networks:
    - custom-network
    tty: true
  mongodb:
    image: mongo:latest
    volumes:
      - backend-mongodb:/data/db
    networks:
    - custom-network
networks:
  custom-network:
    driver: bridge
    ipam: 
      driver: default
      config: 
      - subnet: "192.168.128.0/24"
        gateway:  "192.168.128.1"
volumes:
  backend-mongodb:
